name: bioskop_app
description: A simple bioskop booking app (dummy data)
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.18.0
  http: ^0.13.5
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  google_fonts: ^4.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/